<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>

<meta name="Description" content="Irrgation System based on RaspberryPI board" />
<meta name="Keywords" content="your, keywords" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="Distribution" content="Global" />
<meta name="Author" content="Michele Pavan - michele.pavan@gmail.com" />
<meta name="Robots" content="index,follow" />

<link rel="stylesheet" href="/raspberry/images/PixelGreen.css" type="text/css" />

<title>GardenPi Irrigation</title>
	
</head>

<body>
<!-- wrap starts here -->
<div id="wrap">

	<div id="header"><div id="header-content">	
		
		<h1 id="logo"><a href="index.py" title="">GardenPI</a></h1>	
		<h2 id="slogan">Rasberry Pi Irrigation system</h2>		
		
		<!-- Menu Tabs -->
		<ul>
			<li><a href="/raspberry/index.py" id="current">Monitor</a></li>
			<li><a href="/raspberry/manual.py">Manual</a></li>
			<li><a href="/raspberry/config.py">Setup</a></li>
			<li><a href="/raspberry/stopall.py">Stop All</a></li>
			<li><a href="/raspberry/about.py">About</a></li>			
		<BR>
			<li><a href="/raspberry/rain.py">Rain</a></li>
			<li><a href="/raspberry/temp.py">Temperature</a></li>
		</ul>		
						
	
	</div></div>
	
	<div class="headerphoto"></div>
	
	<!-- content-wrap starts here -->
	<div id="content-wrap"><div id="content">		