<body>
<!DOCTYPE html>
<html>
	<head>
	<title>GardenPi Irragation</title>
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.0a1/jquery.mobile-1.0a1.min.css" />
	<script src="http://code.jquery.com/jquery-1.4.3.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.0a1/jquery.mobile-1.0a1.min.js"></script>

	<!-- jQMDateBox DateTime Picker module-->
	<link rel="stylesheet" type="text/css" href="http://cdn.jtsage.com/datebox/latest/jqm-datebox.min.css">
	<script type="text/javascript" src="http://cdn.jtsage.com/datebox/latest/jqm-datebox.core.min.js"></script>
	<script type="text/javascript" src="http://dev.jtsage.com/cdn/datebox/latest/jqm-datebox.mode.flipbox.min.js"></script>



</head>
<body>

<div data-role="page">

	<div data-role="header">
		<h1>Raspberry Irrigation System</h1>
	</div>
	<!-- /header -->
	<ul data-role="listview" data-inset="true">
		<li><a href="/raspberry/index.py" id="current">Monitor</a></li>
		<li><a href="/raspberry/manual.py">Manual</a></li>
		<li><a href="/raspberry/stopall.py">Stop All</a></li>
		<li><a href="/raspberry/rain.py">Rain Log</a></li>
		<li><a href="/raspberry/temp.py">Temperature</a></li>
		<li><a href="/raspberry/config.py">Setup</a></li>
		<li><a href="/raspberry/about.py">About</a></li>			
	</ul>		

	<div data-role="content">
		<p>
	<!-- /content -->


						
	
